//
// Created by mf on 8/10/26.
//

#ifndef RELACJEOBIEKTOWEIDZIEDZICZENIZAWANSOWANE_OSOBA_H
#define RELACJEOBIEKTOWEIDZIEDZICZENIZAWANSOWANE_OSOBA_H


class Osoba {

};


#endif //RELACJEOBIEKTOWEIDZIEDZICZENIZAWANSOWANE_OSOBA_H
